version: '3'
services:
  ivory_front_office:
    build: "./ivory-front-office"
    depends_on:
      - redis
      - ivory_services
    expose:
      - "3000"
    networks:
      - dev_net
    env_file:
      - "./ivory-front-office/.env"
    environment:
      PORT: 3000
      REDIS_ENABLED: "true"
      REDIS_PORT: 6379
      REDIS_HOST: redis
      SERVICE_API_ENABLED: "true"
      SERVICE_API_PORT: 3010
      SERVICE_API_HOST: ivory_services
  ivory_services:
    build: "./ivory-services"
    depends_on:
      - postgres
    ports:
      - "3010:3010"
    networks:
      - dev_net
    volumes:
      - cachedata:/data
    env_file:
      - "./ivory-services/.env"
    environment:
      PORT: 3010
      POSTGRES_ENABLED: "true"
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  postgres:
    image: "postgres:11.4-alpine"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - dev_net
    volumes:
      - dbdata:/var/lib/postgres
  redis:
    image: "redis:5.0.5-alpine"
    ports:
      - "6379:6379"
    networks:
      - dev_net
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.nginx:/etc/nginx/nginx.conf:ro
    depends_on:
      - ivory_front_office
    ports:
      - "4000:4000"
    networks:
      - dev_net

networks:
  dev_net:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
